name: CI-iOS

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.9.1+hotfix.6'
        channel: 'stable'
    - name: Upgrade flutter
      run: |
        flutter channel stable
        flutter upgrade
    - name: flutter doctor
      run: |
        flutter doctor -v
    - name: flutter depencency package get
      run: |
        flutter pub get
    - name: Build development package using fastlane
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_CERT_REPO: ${{ secrets.FASTLANE_CERT_REPO }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
        MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
      working-directory: ./ios
      run: |
        pod install
        fastlane beta
    - name: Test app on apptest.ai
      uses: forcemax/apptestai-test@v1
      with:
        accesskey: ${{ secrets.APPTESTAI_KEY }}
        projectid: 1089
        packagefile: ios/Runner.ipa
